let catalog,docs=[],items=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pick=a=>a[Math.floor(Math.random()*a.length)];
const people=['テスト 太郎','サンプル 花子','架空 一郎','テスト 美咲','サンプル 健'],companies=['サンプルテクノ株式会社','テスト商事株式会社','サンプル物流株式会社','架空フーズ株式会社','テストワークス株式会社'],products=['サンプル機器 A-100','テスト端末 B-20','架空商品 C-300','サンプル製品 D-8'];
fetch('data/catalog.json').then(r=>r.json()).then(x=>{catalog=x;fill($('#industry'),x.industries,'業種を選択')});
function fill(el,a,p){el.innerHTML='';el.add(new Option(p,''));(a||[]).forEach(x=>el.add(new Option(x.name,x.id)));el.disabled=!a}
function ind(){return catalog?.industries.find(x=>x.id===$('#industry').value)} function job(){return ind()?.jobs.find(x=>x.id===$('#job').value)}
$('#industry').onchange=()=>{fill($('#job'),ind()?.jobs,'職種を選択');fill($('#scene'),null,'職種を先に選択');show([])};
$('#job').onchange=()=>{fill($('#scene'),job()?.scenes,'業務・利用シーンを選択');show([])};
$('#scene').onchange=()=>show(job()?.scenes.find(x=>x.id===$('#scene').value)?.documents||[]);
function show(a){docs=a;$('#documents').className=a.length?'':'empty';$('#documents').innerHTML=a.length?a.map((d,i)=>'<label class="doc"><input type="checkbox" class="dsel" value="'+i+'" checked><strong>'+d.name+'</strong><span class="fmt">'+d.formats.map(x=>x.toUpperCase()).join(' / ')+'</span><p>'+d.description+'</p><div class="tags">'+d.fields.map(x=>'<span class="tag">'+x+'</span>').join('')+'</div></label>').join(''):'業務・利用シーンを選択してください。'}
function val(f,i){let n=i+1;if(/会社|顧客|配送先/.test(f))return pick(companies);if(/担当|参加者|受講者/.test(f))return pick(people);if(/製品|商品/.test(f))return pick(products);if(/日|日時|対象月/.test(f))return '2026-'+String(1+n%12).padStart(2,'0')+'-'+String(1+n%27).padStart(2,'0');if(/ID|番号|コード|ロット/.test(f))return 'TEST-'+String(n).padStart(5,'0');if(/率|進捗/.test(f))return (20+n%79)+'%';if(/数|件|数量|時間|金額|単価|来店/.test(f))return String(10+(n*37)%9000);if(/ステータス|状況/.test(f))return pick(['対応中','確認中','完了']);if(/判定/.test(f))return pick(['合格','要確認']);return pick(['テスト用の架空情報です','標準手順に従って対応','特記事項なし','確認のうえ対応を実施']);}
$('#generate').onclick=()=>{let ds=$$('.dsel:checked').map(x=>docs[+x.value]),fmts=$$('input[name=fmt]:checked').map(x=>x.value),count=+$('input[name=count]:checked').value;if(!ds.length||!fmts.length)return alert('ドキュメントと形式を選択してください。');items=[];for(let i=0;i<count;i++){let d=ds[i%ds.length],f=fmts[i%fmts.length],data={};d.fields.forEach(x=>data[x]=val(x,i));items.push({d,f,data,name:d.name+'_'+String(i+1).padStart(3,'0')+'.'+f})}render()};
function render(){$('#resultPanel').hidden=false;$('#count').textContent=items.length+'件';$('#results').innerHTML=items.map((x,i)=>'<div class="result"><input type="checkbox" class="rsel" value="'+i+'"><span>'+x.name+'</span><b>'+x.f.toUpperCase()+'</b><span class="actions"><button onclick="preview('+i+')">プレビュー</button><button onclick="downloadOne('+i+')">保存</button></span></div>').join('');$('#resultPanel').scrollIntoView({behavior:'smooth'})}
window.preview=i=>{let x=items[i];$('#previewBody').innerHTML='<h2>'+x.d.name+'</h2><p>'+x.d.description+'</p><table class="ptable">'+Object.entries(x.data).map(([k,v])=>'<tr><td>'+k+'</td><td>'+v+'</td></tr>').join('')+'</table><p class="note">TEST DATA ONLY — 架空データ</p>';$('#preview').showModal()};
$('#all').onclick=()=>$$('.rsel').forEach(x=>x.checked=true);$('#zip').onclick=async()=>{let ids=$$('.rsel:checked').map(x=>+x.value);if(!ids.length)return alert('ファイルを選択してください。');let z=new JSZip();for(let i of ids)z.file(items[i].name,await make(items[i]));save(await z.generateAsync({type:'blob'}),'test-documents.zip')};window.downloadOne=async i=>save(await make(items[i]),items[i].name);
function save(b,n){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function make(x){if(x.f==='xlsx'){let ws=XLSX.utils.aoa_to_sheet([['TEST DATA ONLY','架空データ'],...Object.entries(x.data)]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'TestData');return new Blob([XLSX.write(wb,{bookType:'xlsx',type:'array'})])}
if(x.f==='docx'){let D=docx,children=[new D.Paragraph({text:x.d.name,heading:D.HeadingLevel.TITLE}),new D.Paragraph('TEST DATA ONLY — 本文書は架空データです。'),...Object.entries(x.data).map(([k,v])=>new D.Paragraph({children:[new D.TextRun({text:k+'：',bold:true}),new D.TextRun(String(v))]}))];return D.Packer.toBlob(new D.Document({sections:[{children}]}))}
if(x.f==='pptx'){let p=new PptxGenJS(),s=p.addSlide();s.addText(x.d.name,{x:.7,y:.6,w:8,h:.5,fontSize:24,bold:true});s.addText('TEST DATA ONLY — 架空データ',{x:.7,y:1.2,w:8,h:.3,fontSize:10});s.addText(Object.entries(x.data).map(([k,v])=>k+'：'+v).join('\n'),{x:.8,y:1.7,w:8,h:4,fontSize:15});return new Blob([await p.write({outputType:'arraybuffer'})])}
let p=new window.jspdf.jsPDF();p.setFontSize(16);p.text('TEST DOCUMENT / '+x.d.id,15,18);p.setFontSize(9);p.text('TEST DATA ONLY',15,26);let y=36;Object.entries(x.data).forEach(([k,v])=>{p.text(k.replace(/[^\x20-\x7E]/g,'[JP]')+': '+String(v).replace(/[^\x20-\x7E]/g,'[JP]'),15,y);y+=8});return p.output('blob')}